canvas/toolgrid: Remove (unused) mouse press event tracking
Fix an `AttributeError: 'NoneType' object has no attribute 'underMouse'`
in the `ToolButtonEventListener.eventFilter`. The mouse press tracking
was not even used so the class was removed, merging the parts that were
used into `ToolGrid` itself.

Transplanted-from: biolab/orange3@75df30a294bf25367b9f57c7ef3e556e63b197c1